// Populer Muzik (POP) Chunk - 501 Songs
(function() {
  window.CATALOG_CHUNKS = window.CATALOG_CHUNKS || [];
  window.CATALOG_CHUNKS.push({
    p: [
      "https://www.notaarsivleri.com/NotaMuzik/",
      "https://www.sahaney.com/nota-arsivi/",
      "https://www.notaarsivleri.com/"
    ],
    r: [
["Ağla Gözlerim Ağla Zamanıdır","","","","Orhan Gencebay","Orhan Gencebay","0:agla_gozlerim_agla_zamanidir.pdf","POP"],
["Ağlarsa Anam Ağlar","","","","Suat Sayın","Suat Sayın","0:aglarsa_annem_aglar.pdf","POP"],
["Agora Meyhanesi","","","","İsmet Nedim Saatçi","Onur Şenli","0:agora_meyhanesi.pdf","POP"],
["Ah Bir Ataş Ver","","","","","","0:ah_bir_atas_ver.pdf","POP"],
["Ah Le Yar Yar","","","","Yücel Arzen","Hüseyin Turan","0:ah_le_yar.pdf","POP"],
["Akdeniz Akşamları","","","","Serhan Kelleözü","","0:akdeniz_aksamlari.pdf","POP"],
["Aklım Karıştı","","","","Kenan Doğulu","","0:aklim_karisti.pdf","POP"],
["Akşam Olur Gizli Gizli Ağlarım","","","","Suat Sayın","Halil Soyuer","0:aksam_olur_gizli_gizli_aglarim.pdf","POP"],
["Alıştım Sana Birtanem","","","","Selami Şahin","Selami Şahin","0:alistim_sana_birtanem.pdf","POP"],
["Allah\u0027ın emriyle Peygamber kavliyle","","","","Orhan Gencebay","Orhan Gencebay","0:allah-in-emriylepdf1572120530.pdf","POP"],
["Allahım Benden Çok Mu Sevdin","","","","Yaşar Güvenir","Yaşar Güvenir","0:allahim_benden_cok_mu_sevdin.pdf","POP"],
["Aman Kimseler Duymasın","","","","","","0:aman_kimseler_duymasin.pdf","POP"],
["Anılar Anılar","","","","Coşkun Sabah","A. Selçuk İlkan -C.Sabah","0:anilar.pdf","POP"],
["Ankaranın Taşına Bak","","","","Ali Cihat Aşkın","","0:ankaranin_tasina_bak.pdf","POP"],
["Anlamazdın (Piano için)","","","","Esin Engin","Esin Engin","0:ayla-dikmen-anlamazdin-pianopdf1456685191.pdf","POP"],
["Anlamazdın","","","","Esin Engin","Esin Engin","0:anlamazdin.pdf","POP"],
["Anlasana","","","","Haluk Levent","Haluk Levent","0:anlasana.pdf","POP"],
["Anlıyorsun Değil Mi","","","","","","0:anliyorsun_degilmi.pdf","POP"],
["Arada Sırada","","","","Sinan Akçıl","Sinan Akçıl","0:arada_sirada.pdf","POP"],
["Arap Saçı","","","","Özer Şenay","Özer Şenay","0:arap-sacipdf1648818904.pdf","POP"],
["Arda Boylarında Kırmızı Erik","","","","","","0:arda_boylarinda_kirmizi_erik.pdf","POP"],
["Arım Balım Peteğim","","","","İsmet Nedim Saatçi","","0:arim_balim_petegim.pdf","POP"],
["Arkadaş","","","","Şanar Yurdatapan","Şanar Yurdatapan","0:arkadas.pdf","POP"],
["Arpa Buğday Daneler","","","","","","0:arpa_bugday_daneler.pdf","POP"],
["Artık Senin Adını Zehir Saçan Aşkını","","","","İsmet Nedim Saatçi","İsmet Nedim Saatçi","0:artik_senin_adini.pdf","POP"],
["Artık Sevmeyeceğim","","","","Suat Sayın","Suat Sayın","0:artik_sevmeyecegim.pdf","POP"],
["Asi Dizi Müziği","","","","","","0:asi_dizi_muzigi.pdf","POP"],
["Asırlardır Yalnızım","","","","Kayahan Acar","Kayahan Acar","0:asirlardir_yalnizim.pdf","POP"],
["Aşk yolunda harcayacak gücüm yok","","","","Muzaffer Özpınar","Vural Şahin","0:geckaldinpdf1512504986.pdf","POP"],
["Aşkımız Bir Roman","","","","Ali İhsan Kısaç","Ali İhsan Kısaç","0:askimiz_bir_roman.pdf","POP"],
["Aşkımız Yalanmıydı","","","","Mazlum Çimen","Yasemin Göksu","0:askimiz_yalanmiydi.pdf","POP"],
["Aşkımla Oynama Kumar Değildir","","","","İsmet Nedim Saatçi","Mehmet Erbulan","0:askimla_oynama_kumar_degildir.pdf","POP"],
["Aşkın Kanununu Yazsam Yeniden","","","","Sadettin Öktenay","Mehmet Erbulan","0:askin_kanununu.pdf","POP"],
["Aşkınla Yana Yana","","","","İsmet Nedim Saatçi","Mehmet Erbulan","0:askinla_yana_yana.pdf","POP"],
["Ateşim Var Külüm Yok","","","","Suat Sayın","Suat Sayın","0:atesim_var_kulum_yok.pdf","POP"],
["Ay Yüzlüm","","","","","","0:ay_yuzlum.pdf","POP"],
["Ayılana Gazoz","","","","","","0:ayilana_gazoz.pdf","POP"],
["Ayrılığın Böylesi (Bırakında yaşayalım)","","","","Orhan Gencebay","Orhan Gencebay","0:ayriligin-boylesi-gorulmus-bir-sey-degil-birakinda-yasayalimpdf1560586913.pdf","POP"],
["Ayrılık Kolay Değil","","","","Suat Sayın","Suat Sayın","0:ayrilik_kolay_degil.pdf","POP"],
["Ayrılmalıyız Artık","","","","Teoman Alpay","Teoman Alpay","0:ayrilmaliyiz_artik.pdf","POP"],
["Bağrımda bir ateş var ne bileceksin","","","","Orhan Gencebay","Orhan Gencebay","0:bagrimda-bir-ates-var-ne-bileceksinpdf1560197732.pdf","POP"],
["Baharı Beklerken Ömrüm kış oldu","","","","Selçuk Tekay","Sami Derintuna","0:bahari_beklerken_omrum_kis_oldu.pdf","POP"],
["Baharı Bekleyen Kumrular Gibi","","","","Coşkun Sabah","Ali Tekintüre","0:bahari_bekleyen_kumrular_gibi.pdf","POP"],
["Bahtıma hep soruyorum (Kördüğüm)","","","","Orhan Gencebay","Orhan Gencebay","0:bahtima-hep-soruyorum-kordugumpdf1560193958.pdf","POP"],
["Bak Bir Varmış Bir Yokmuş","","","","İlhan Gencer","","0:bak_bir_varmis_bir_yokmus.pdf","POP"],
["Bana bir dünya ver cennetim olsun","","","","Esin Engin","Füsun Ocakçıoğlu","0:bana-bir-dunya-verpdf1456690017.pdf","POP"],
["Bana Yalan Söylediler","","","","Jose Feliciano","Fikret Şeneş","0:bana_yalan_soylediler.pdf","POP"],
["Batarken Ufukta Bir Akşam Güneşi","","","","Orhan Gencebay","Orhan Gencebay","0:batarken_ufukta_bir_aksam_gunesi.pdf","POP"],
["Batsın Bu Dünya","","","","Orhan Gencebay","","0:batsin_bu_dunya.pdf","POP"],
["Bebeğim","","","","","","0:bebegim.pdf","POP"],
["Bekar Gezelim","","","","","","0:bekar_gezelim.pdf","POP"],
["Bekle Beni Geliyorum","","","","","","0:bekle_beni_geliyorum.pdf","POP"],
["Bekle dedi gitti (Piano için)","","","","Kaan Tangöze","","0:bekle-dedi-gittipdf1532514829.pdf","POP"],
["Beklemekten yoruldum","","","","İsmet Nedim Saatçi","Nur İncegül","0:beklemekten-yoruldum-icimde-kanimdasin-pdf1639003755.pdf","POP"],
["Ben Böyleyim","","","","Armando Manzareno","Ümit Aksu","0:ben_boyleyim.pdf","POP"],
["Ben Her Eylül O Parkta (Nartanem)","","","","Yusuf Nalkesen","Yusuf Nalkesen","0:benhereyluloparktapdf1481566810.pdf","POP"],
["Ben Küskünüm Feleğe","","","","Baki Duyarlar","","0:ben_kuskunum_felege.pdf","POP"],
["Ben ne yaptım kendi kendime","","","","Orhan Gencebay","Orhan Gencebay","0:ben-ne-yaptim-kendi-kendimepdf1560198085.pdf","POP"],
["Ben Özgürüm","","","","Nil Karaibrahimgil","Nil Karaibrahimgil","0:ben_ozgurum.pdf","POP"],
["Ben Seni Uzaklarda Sevdim","","","","Cevdet Bağca","","0:ben_seni_uzaklarda.pdf","POP"],
["Ben Varım","","","","","Fikret Şeneş","0:ben_varim.pdf","POP"],
["Beni Al","","","","","","0:beni_al.pdf","POP"],
["Beni Bekledinse Yağmurda Karda","","","","Onur Akın","Onur Akın","0:beni_bekledinse_yagmurda_karda.pdf","POP"],
["Benim boynum hep böyle bükülü mü kalacak","","","","Orhan Gencebay","Orhan Gencebay","0:benim-boynum-hep-boyle-bukulu-mu-kalacak-sen-de-bizdensin-pdf1572121576.pdf","POP"],
["Benim Dünyam","","","","Orhan Gencebay","Orhan Gencebay","0:sen-benim-icicde-bir-korkulu-ruya-benim-dunyampdf1560340433.pdf","POP"],
["Beyaz Giyme söz olur (Piano İçin )","","","","","","0:beyaz-giyme-soz-olur-piano-turca-cover-orjinalpdf1512480663.pdf","POP"],
["Bilmesin o felek seni çok sevdiğimi","","","","Orhan Gencebay","Orhan Gencebay","0:bilmesin-o-felek-seni-cok-sevdigimipdf1637346505.pdf","POP"],
["Bilmez insan kadrini","","","","Orhan Gencebay","Orhan Gencebay","0:bilmez-insan-kadrinipdf1560193981.pdf","POP"],
["Bilmiyorum Seninle Sonumuz ne olacak","","","","Selami Şahin","Selami Şahin","0:bilmiyorum_seninle_sonumuz_ne_olacak.pdf","POP"],
["Bir Aslan Miyav Dedi","","","","Kayahan Acar","","0:bir_aslan_miyav_dedi.pdf","POP"],
["Bir Bakış Baktın Kalbimi Yaktın","","","","Cevat Ultanır","","0:bir_bakis_baktin_kalbimi_yaktin__bagdat_yolu_.pdf","POP"],
["Bir Çapkına Yangınım","","","","Kadri Cerrahoğlu","Kadri Cerrahoğlu","0:bir_capkina_yanginim.pdf","POP"],
["Bir Daha Aşık Olmayacağım","","","","İsmet Nedim Saatçi","Mehmet Erbulan","0:bir_daha_asik_olmayacagim.pdf","POP"],
["Bir Efsane","","","","Mithat Körler","","0:bir_efsane.pdf","POP"],
["Bir Fincan Kahve Olsam","","","","Selâhattin Sarıkaya","Ülkü Aker","0:bir_fincan_kahve_olsam.pdf","POP"],
["Bir Garip Yolcuyum","","","","Yıldırım Gürses","Yıldırım Gürses","0:bir_garip_yolcuyum_hayat_yolunda.pdf","POP"],
["Bir Görüşte Aşık Oldum","","","","Orhan Gencebay","Orhan Gencebay","0:bir-goruste-asik-oldum-sana-delicepdf1560358226.pdf","POP"],
["Bir gün neş\u0027e bir gün keder","","","","Esin Engin","Halit Çelikoğlu","0:birgunnesebirgunkederpdf1456690180.pdf","POP"],
["Bir Güneş Doğmayacak","","","","Haydar Telhüner","Haydar Telhüner","0:bir_gunes_dogmayacak.pdf","POP"],
["Bir ışık var gözlerinde","","","","Orhan Gencebay","Orhan Gencebay","2:populer-muzik/495.html","POP"],
["Bir İstanbul Masalı","","","","","","0:bir_istanbul_masali.pdf","POP"],
["Bir Kere Baktın","","","","İsmet Nedim Saatçi","Mehmet Erbulan","0:bir_kere_baktin.pdf","POP"],
["Bir Masal Bu Dalgalara....(Alev Alev)","","","","Ramazan Günhan","","0:bir_masal_bu_sahillere_vuran_dalgalar.pdf","POP"],
["Bir Meçhul Âleme Giderken ..","","","","Orhan Gencebay","Orhan Gencebay","0:bir_mechul_aleme_giderken_dunya.pdf","POP"],
["Bir Rüzgâr Gibi Geçti","","","","D.Gönenç - Y. Arzen","","0:bir_ruzgar_gibi.pdf","POP"],
["Bir Şarkısın Sen (Samanyolu)","","","","Metin Bükey","Teoman Alpay","0:bir_sarkisin_sen.pdf","POP"],
["Bir Teselli Ver","","","","Orhan Gencebay","Orhan Gencebay","0:bir_teselli_ver.pdf","POP"],
["Bir yol tuttum gidiyorum","","","","Orhan Gencebay","Orhan Gencebay","0:bir-yol-tuttum-gidiyorumpdf1560194080.pdf","POP"],
["Bir Zaman Ağlayıp Koştum Peşinden","","","","Orhan Gencebay","Orhan Gencebay","0:bir-zaman-aglayip-kostum-pesindenpdf1560358181.pdf","POP"],
["Bir Zamanlar Bir Yâr Vardı","","","","Muzaffer Özpınar","Muzaffer Özpınar","0:bir_zamanlar_bir__yar_vardi.pdf","POP"],
["Birtanem","","","","Cengiz İmren","","0:birtanem.pdf","POP"],
["Birtane","","","","Latif Doğan","Latif Doğan","0:birtane.pdf","POP"],
["Bitmese","","","","Ergin Kızılay","Ülkü Aker","0:bitmese.pdf","POP"],
["Bitmeyen mutluluk","","","","Esin Engin","Aşkın Tuna","0:bitmeyenmutlulukpdf1456690222.pdf","POP"],
["Biz Ayrılamayız","","","","Mahmut Oğul","","0:biz_ayrilamayiz.pdf","POP"],
["Bizim Mahâlle Aşağı Ki Mahâlle","","","","","","0:bizim_mahalle_asgiki_mahalle.pdf","POP"],
["Blue Bossa","","","","","","0:blue_bossa.pdf","POP"],
["Boş Kalan Çerçeve","","","","İsmet Nedim Saatçi","Şendoğan Arda","0:bos_cerceve.pdf","POP"],
["Boş Sokak","","","","","","0:bos_sokak.pdf","POP"],
["Böyle Ayrılık Olmaz","","","","Adnan Ergil","Adnan Ergil","0:boyle_ayrilik_olmaz.pdf","POP"],
["Bu Aşk Bitmez","","","","Cahit Berkay","Ömer Faruk Güney","0:bu_ask_bitmez.pdf","POP"],
["Bu Devirde Kimse Şah Değil","","","","Serdar Ortaç","Serdar Ortaç","0:bu_devirde_kimse_sah_degil.pdf","POP"],
["Bu Gece Son Gecemiz","","","","Teoman Alpay","H. Özcan Balım","0:bu_gece_son_gecemiz.pdf","POP"],
["Bu gün bir gariplik var ki üstümde","","","","Orhan Gencebay","Orhan Gencebay","0:bugun-bir-gariplik-var-ki-ustumde-seni-ariyorumpdf1560194131.pdf","POP"],
["Bu gün gönlümde bir başkalık var","","","","Orhan Gencebay","Orhan Gencebay","0:bu-gun-gonlumde-bir-baskalik-varpdf1560198182.pdf","POP"],
["Bu Ne Sevgi Ah Bu Ne Izdırap","","","","Abdullah Yüce","Abdullah Yüce","0:bu_ne_sevgi_ah_bu_ne_izdirap(1).pdf","POP"],
["Bulamazsın Benim Gibi Seveni","","","","Selami Şahin","Selami Şahin","0:bulamazsin.pdf","POP"],
["Bunca Yıl Habersiz","","","","Orhan Gencebay","Orhan Gencebay","0:bunca_yil_habersiz.pdf","POP"],
["Bunca yıl herkesten kaçtın","","","","Fikret Kızılok","","0:gonulpdf1512505081.pdf","POP"],
["Caddelerde Rüzgar","","","","","","0:caddelerde_ruzgar.pdf","POP"],
["Çadırımın Üstüne","","","","","","0:cadirimin_ustune.pdf","POP"],
["Çal Kanunum Çal","","","","Yıldırım Gürses","Cengizhan Mutlu","0:cal_kanunum_cal.pdf","POP"],
["Çalıkuşu","","","","Yesari Asım Arsoy","","0:calikusu.pdf","POP"],
["Çalıkuşu (Dizi müziği) (Piano için)","","","","Esin Engin","Esin Engin","0:calikusu-dizi-muzigi-pianopdf1456685572.pdf","POP"],
["Canbaz","","","","","","0:canbaz.pdf","POP"],
["Canım Efendim","","","","Vedat Yıldırımbora","","0:canim_efendim.pdf","POP"],
["Cano Cano","","","","","","0:cano_cano.pdf","POP"],
["Cav Bella","","","","","","0:cav_bella.pdf","POP"],
["Cennet","","","","","","0:cennet.pdf","POP"],
["Cesaretim Var","","","","Serdar Ortaç","Serdar Ortaç","0:cesaretim_var.pdf","POP"],
["Cici Kız","","","","Erol Sayan","Naci Sayan","0:cici_kiz.pdf","POP"],
["Çifte Telli","","","","","","0:cifte_telli.pdf","POP"],
["Çık Git Benim Dünyamdan","","","","Kemal","","0:cik_git.pdf","POP"],
["Çocuk Oldum","","","","Rıfat Şanlıel","A. Tekin Türe","0:cocuk_oldum.pdf","POP"],
["Çok ararsın bulamazsın benim gibi bir  sevgili","","","","Orhan Gencebay","Orhan Gencebay","0:cok-ararsin-bulamazsin-benim-gibi-bir-sevgilipdf1560194184.pdf","POP"],
["Çökertme","","","","","","0:cokertme.pdf","POP"],
["Çökertmeden çıktım da halilim (Piano için)","","","","Rüştü Gür (Kaynak Kişi)","","0:cokertmeden-ciktim-da-halilim-pianopdf1456685723.pdf","POP"],
["Çöpcüler","","","","","","0:copculer.pdf","POP"],
["Dağlar Dağlar","","","","Barış Manço","Barış Manço","0:daglar_daglar.pdf","POP"],
["Dağlar Kızı Reyhan","","","","Fikret Amirov","Talat Eyyubov","2:populer-muzik/114.html","POP"],
["Dağların Karı Yetmez","","","","Selçuk Balcı","","0:daglarin_kari_yetmez.pdf","POP"],
["Darıldın Mı Cicim Bana","","","","","","0:darildin_mi_cicim_bana(1).pdf","POP"],
["Değdi Saçlarıma Bahar Gülleri (Piano için)","","","","Bekirof (Azerî)","","0:nazende-sevgilim-pianopdf1456687163.pdf","POP"],
["Değişmem gerek şu düzenimi","","","","Orhan Gencebay","Orhan Gencebay","0:degismem-gerek-su-duzenimipdf1560194237.pdf","POP"],
["Değmen Benim Gamlı Yaslı ...","","","","Derleyen - M.Erenler","Kaynak - Abbas Öz","0:deymen_benim_gamli_yasli_gonlume.pdf","POP"],
["Deniz Ne Kadar Güzel Hoş","","","","F.Ce. Curtıs","","0:deniz_ne_kadar_guzel_hos.pdf","POP"],
["Deniz Ve Mehtap","","","","M.Jourdan-A.Borly-A.Canfora","Fecri Ebcioğlu","0:deniz_ve_mehtap.pdf","POP"],
["Dert Bende Derman Sende","","","","Vedat Yıldırımbora","Vedat Yıldırımbora","0:dert_bende_derman_sende.pdf","POP"],
["Dert Çekmeye Gidiyorum","","","","Coşkun Sabah","Coşkun Sabah","0:dert_cekmeye_gidiyorum.pdf","POP"],
["Dert Ortağım Benim","","","","Norayr Demirci","Ülkü Aker","0:dert_ortagim_benim.pdf","POP"],
["Dertler Benim Olsun","","","","Orhan Gencebay","Orhan Gencebay","0:dertler_benim_olsun.pdf","POP"],
["Devlerin Aşkı Büyük Olur","","","","Halil Karaduman","A. Aşkın Tuna","0:devlerinaskibuyukolurpdf1517162788.pdf","POP"],
["Dido","","","","Kazım Koyuncu","","0:didopdf1517166845.pdf","POP"],
["Dil Yarası","","","","Orhan Gencebay","Orhan Gencebay","0:kim-bilecek-daha-neler-neler-bekliyor-ikimizi-dil-yarasipdf1560193198.pdf","POP"],
["Dilek Taşı","","","","Gülden Karaböcek","Ali Tekin Türe","0:dilek_tasi.pdf","POP"],
["Dilerim Tanrıdan Gülmesin Yüzün (Beddua)","","","","Coşkun Sabah","A. İlkan San","0:dilerim_tanridan_gulmesin_yuzun__beddua_.pdf","POP"],
["Divane Aşık Gibi","","","","Karabulut","","0:divane_asik_gibi.pdf","POP"],
["Doğum Günüm","","","","Yunus Bülbül","","0:dogum_gunum.pdf","POP"],
["Dokunma kırılır kalbim dokunma","","","","Orhan Gencebay","Orhan Gencebay","0:dokunma-kirilir-kalbim-dokunmapdf1560194581.pdf","POP"],
["Dönsen De Artık Sevemem Seni","","","","Mehmet Bürün","Mehmet Bürün","0:donsen_de_artik_sevemem_seni(1).pdf","POP"],
["Dost Bildiklerim","","","","","","0:dost_bildiklerim.pdf","POP"],
["Düğününde Ağladım","","","","Selahattin Sarıkaya","Selahattin Sarıkaya","0:dugununde_agladim.pdf","POP"],
["Düm Tek Tek (Hadise)","","","","","","0:dum_tek_tek_hadise.pdf","POP"],
["Dün Akşam Yine Benim Yollarıma bakmışsın","","","","Selami Şahin","Selami Şahin","0:dun_aksam_yine_benim_yollarima_bakmissin.pdf","POP"],
["Dün Gece Seni Düşündüm","","","","Coşkun Sabah","Tunç Kemâl","0:dun_gece_seni_dusundum_durdum.pdf","POP"],
["Dünya","","","","K. Taşçeşme","","0:dunya.pdf","POP"],
["Dünya da aşk deninlen kelime yalan","","","","Suat Sayın","","0:dunyadaaskdenenkelimeyalanpdf1555836523.pdf","POP"],
["Dünya Dönüyor Sen Ne Dersen De","","","","Marc Aryan","Fecri Ebcioğlu","0:dunya_donuyor.pdf","POP"],
["Dünya Dünya","","","","Orhan Gencebay","Orhan Gencebay","0:sevda-bu-kara-sevda-cok-seviyorum-dunya-dunyapdf1560415458.pdf","POP"],
["Dünya gözlerimden ağlıyor gibi","","","","Orhan Gencebay","Orhan Gencebay","0:dunya-gozlerinde-agliyor-gibi-askimizin-duasi-pdf1572121661.pdf","POP"],
["Dünyâ Handır   (Goca Dünya)","","","","Orhan Gencebay","Orhan Gencebay","0:dunya_handir_han_icinde.pdf","POP"],
["Dünya zâlim bir değirmen","","","","Mahmut Oğul","A. Selçuk İlkan","0:dunyazalimpdf1512504898.pdf","POP"],
["Düşler Sokağı","","","","Nadir Göktürk","Hüsnü Arkan","0:dusler_sokagi.pdf","POP"],
["Ederlezi (Balkan Halk Ezgisi) (Piano İçin)","","","","Goran Bregovic (Düzenleme)","","0:goran-bregovic-ederlezi-pianopdf1456686002.pdf","POP"],
["Efendim    (İki Elim Kanda Olsa Gelirim)","","","","Selami Şahin","Selami Şahin","0:efendim.pdf","POP"],
["Eller","","","","Yıldırım Gürses","Mustafa Sevilen","0:eller.pdf","POP"],
["Ellerimde Çiçekler","","","","","","0:ellerimde__cicekler.pdf","POP"],
["Ellerimden ellerin ayrılmasın Azize","","","","Suat Sayın","Birsin Kozluca","0:ellerimden_ellerin_ayrilmasin__azize_.pdf","POP"],
["Elvedâ Bütün Hâtıralar","","","","Mutsel Öztürk","Mutsel Öztürk","0:elvedabutunhatiralarpdf1510936786.pdf","POP"],
["Elveda Meyheneci","","","","Kerem Güney","H. Münir Ebcioğlu","0:elveda_meyhaneci.pdf","POP"],
["Emrin Olur","","","","Kayahan Acar","Kayahan Acar","0:emrin_olur.pdf","POP"],
["En büyük sır daha bilinmeyendir","","","","Orhan Gencebay","Orhan Gencebay","0:en-buyuk-sir-daha-bilinmeyendirpdf1637346566.pdf","POP"],
["En son hâtıram","","","","Fehmi Ege","Fehmi Ege","0:en-son-hatirampdf1514412241.pdf","POP"],
["Eskimeyen Dost","","","","Selami Şahin","Ülkü Aker","0:eskimeyen_dost.pdf","POP"],
["Eteğine Yapışmış Sonbahar ....","","","","Halil Karaduman","Attila Şanbay","0:etegine_yapismis_sonbahar_ruzgarlari.pdf","POP"],
["Fabrika Kızı","","","","Bora Ayanoğlu","Bora Ayanoğlu","0:fabrika_kizi.pdf","POP"],
["Farkı Var","","","","Orhan Gencebay","Orhan Gencebay","0:farki_var.pdf","POP"],
["Felek Beni Kul Eyledi","","","","Mustafa Erses","Nâdide Buluç","0:felek_beni_kul_eyledi(1).pdf","POP"],
["Feraye","","","","","","0:feraye.pdf","POP"],
["Feryâd","","","","Yıldırım Gürses","Yıldırım Gürses","0:feryad.pdf","POP"],
["Fikrimden geceler yatabilmirem (Ayrılık)","","","","Ali Selimi","Ali Selimi","0:fikrimden_geceler_yatabilmirem__ayrilik_.pdf","POP"],
["Fikrimin ince gülü (Piano için)","","","","M. İsmail Hakkı Bey","","0:fikrimin-ince-gulu-pianopdf1456685788.pdf","POP"],
["Fırat","","","","İzzet Altınmeşe","İzzet Altınmeşe","0:firat.pdf","POP"],
["Firuze","","","","Atilla Özdemiroğlu","Aysel Gürel","0:firuze.pdf","POP"],
["Fur Elıse","","","","L. Van Beethoven","","0:fur_elise.pdf","POP"],
["Gece Kirpikli Kadın","","","","İlyas Tetik","Zeki Müren","0:gece_kirpikli_kadin.pdf","POP"],
["Geceler Yarim Oldu","","","","Şükrü Tunar","","0:geceler_yarim_oldu(1).pdf","POP"],
["Geceler","","","","","","2:populer-muzik/161.html","POP"],
["Gecelerim","","","","Doğan Canku","Şeref Canku","0:gecelerim.pdf","POP"],
["Gel Desem Döner Mi Sanki","","","","Yıldırım Gürses","Yıldırım Gürses","0:gel-desem-doner-mi-san-kipdf1513678776.pdf","POP"],
["Gidemem","","","","Nokias","","0:gidemem.pdf","POP"],
["Gidiyorsan dönmekte var kalmakta var","","","","Orhan Gencebay","Orhan Gencebay","0:gidiyorsan-donmekte-var-kalmakta-var-zamansiz-ruzgar-pdf1572122137.pdf","POP"],
["Gitme darılıp gitme","","","","Orhan Gencebay","Orhan Gencebay","0:gitme-darilip-gitmepdf1560194641.pdf","POP"],
["Gitme Sana Muhtacım","","","","Selami Şahin","Selami Şahin","0:gitme_sana_muhtacim.pdf","POP"],
["Gittide Gitti","","","","Orhan Gencebay","Orhan Gencebay","0:gittide_gitti.pdf","POP"],
["Gittin Gideli","","","","Edip Akbayram","","0:gittin_gideli.pdf","POP"],
["Godfather","","","","","","0:gotfather.pdf","POP"],
["Gökyüzünde pırıl pırıl sendin","","","","Orhan Gencebay","Orhan Gencebay","0:gokyuzunden-piril-piril-sendinpdf1560194701.pdf","POP"],
["Gölge Etme","","","","Vedat Yılrım Bora","Cemal Safi","0:golge_etme.pdf","POP"],
["Gönül Çelen","","","","Teoman","","0:gonul_celen.pdf","POP"],
["Gönül Sayfam","","","","Kayahan Acar","Kayahan Acar","0:gonul_sayfam.pdf","POP"],
["Gönül  ( Nedir Bu Çektiğin Senden)","","","","Orhan Gencebay","Orhan Gencebay","0:gonul.pdf","POP"],
["Gözlerim Uykuyla Bariştı Sanma","","","","Selçuk Tekay","Cemal Safi","0:gozlerim_uykuyla_baristi_sanma.pdf","POP"],
["Gözlerini Gözlerimden Ayırma Hiç","","","","İsa Coşkuner","","0:gozlerini_gozlerimden_ayirma_hic_ne_olur.pdf","POP"],
["Gözlerini Met etsem","","","","Fehmi Ege","Fehmi Ege","0:gozlerini-metetsempdf1514412163.pdf","POP"],
["Gözlerinin Içine Başka Hayâl Girmesi (Piano için )","","","","Zeki Müren","Sabih Gözen","0:gozlerinin-icine-baska-hayal-girmesin-beklenen-sarki-piano-turca-piyano-yorumu-orjinalpdf1512480927.pdf","POP"],
["Gözüm Kesmiyor","","","","Orhan Gencebay","Orhan Gencebay","0:gozum_kesmiyor.pdf","POP"],
["Gözümde Uyku Var Bu Ne Yorgunluk","","","","Orhan Gencebay","Orhan Gencebay","0:gozumde_uyku_var_bu_ne_yorgunluk.pdf","POP"],
["Gözyaşlarımız Bitti Mi Sandın","","","","Mazhar Alansoy","Mazhar Alanson","0:gozyaslarimiz_bittimi_sandin.pdf","POP"],
["Greensleeves","","","","","","0:greensleeves_solo.pdf","POP"],
["Gül Ağacı Değilem","","","","Necip Mirkelmoğlu","Necip Mirkelamoğlu","0:gul_agaci_degilem(1).pdf","POP"],
["Gül Döktüm Yollarına","","","","Yehuda Badıchı","Uri Barzılaı","0:gul_doktum_yollarina.pdf","POP"],
["Gül güzeli (Piano için)","","","","","","0:leman-sam-gul-guzeli-piano-cover-orjinalpdf1517939320.pdf","POP"],
["Gül Ki Sevgilim","","","","Oğuzhan Koç","","0:gulkisevgilimpdf1784454897.pdf","POP"],
["Gül Penbe","","","","Barış Manço","Barış Manço","0:gul_penbe.pdf","POP"],
["Güldür Yüzümü","","","","Yavuz Taner","Ali Tekin Türe","0:guldur_yuzumu.pdf","POP"],
["Güller Ve Dudaklar","","","","Bora Ayanoğlu","Bora Ayanoğlu","0:guller_ve_dudaklar.pdf","POP"],
["Güllerin İçinden Canım","","","","Mazhar Alanson","Mazhar Alanson","0:gullerin_icinde_canim.pdf","POP"],
["Gülüm","","","","","","0:gulum.pdf","POP"],
["Gülüm Benim","","","","Burhan Bayar","Şakir Askan","0:gulum_benim.pdf","POP"],
["Gülümcan","","","","Murat İşbilen","","0:gulumcan.pdf","POP"],
["Gümüş Gerdanlık","","","","Metin Bükey","Metin Bükey","0:gumus_gerdanlik.pdf","POP"],
["Gün Işığım","","","","Halil Karaduman","A. Aşkın Tuna","0:gun_isigim.pdf","POP"],
["Gün Sensiz Batar Kalp Gizli Kanar","","","","Serkan","Adnan Çoban","0:gun_sensiz_batar_kalp_gizli_kanar.pdf","POP"],
["Güneş","","","","","","0:gunes.pdf","POP"],
["Güneşin En Sıcağında","","","","","","0:gunesin_en_sicaginda.pdf","POP"],
["Günün Birinde","","","","Selahattin Cesur","A. Selçuk İlkan","0:gunun_birinde.pdf","POP"],
["Gurbet Bahtımdan Kara","","","","Suat Sayın","F. Nafiz Çamlıbel","0:gurbet_bahtimdan_kara.pdf","POP"],
["Gurbet Elde Hasta Düştüm Ağlarım","","","","Orhan Gencebay","Orhan Gencebay","0:gurbet-elde-hasta-dustum-aglarimpdf1637346638.pdf","POP"],
["Güzel Gözlerine Bakmaya Doyamam","","","","Adnan Şenses","Adnan Şenses","0:guzel_gozlerine_bakmaya_doyamam.pdf","POP"],
["Hababam Sınıfı","","","","Melih Kibar","Melih Kibar","0:hababam_sinifi_film_muzigi.pdf","POP"],
["Hadi Ben Öfkemi Yenemedim De","","","","Yusuf Nalkesen","Yusuf Nalkesen","0:hadi_ben_ofkemi_yenemedim_de(1).pdf","POP"],
["Hadi Git","","","","Orhan Gencebay","Cemal Safi","0:hadi_git.pdf","POP"],
["Halil İbrahim","","","","Selahattin Aygün","Dursun Ali Akinet","0:halilibrahimpdf1524514598.pdf","POP"],
["Hangi dala el attık ta kurumadı ki","","","","Orhan Gencebay","Orhan Gencebay","0:hangi-dala-el-attik-ta-kurumadi-kipdf1560254767.pdf","POP"],
["Happy Birtday","","","","","","0:happy_birthday.pdf","POP"],
["Haram Geceler","","","","Adnan Ergil","Adnan Ergil","0:haram_geceler.pdf","POP"],
["Hardasan (Piano için )","","","","Feryal Öney","","0:feryal-oney-hardasan-piano-turca-coverpdf1512480779.pdf","POP"],
["Hasret (Piano için)","","","","","","0:hasretpdf1517942078.pdf","POP"],
["Hasretinle Yandı Gönlüm","","","","Yalçın Tura","Yalçın Tura","0:hasretinle_yandi_gonlum.pdf","POP"],
["Hata","","","","","","0:hata.pdf","POP"],
["Hatasız Kul Olmaz","","","","Orhan Gencebay","Orhan Gencebay","0:hatasiz_kul_olmaz_hatamla_sev_beni.pdf","POP"],
["Hâtıralar Sarmış Dört Bir Yanımı","","","","Selçuk Tekay","A. Aşkın Tuna","0:hatiralar_sarmis_dortbir_yanimi.pdf","POP"],
["Hâtıram Olsun","","","","Coşkun Sabah","Coşkun Sabah","0:hatiram_olsun.pdf","POP"],
["Hava Nasıl Oralarda","","","","","","0:hava_nasil_oralarda.pdf","POP"],
["Hayat Bayram Olsa","","","","Kolfgiero","Şenay","0:hayat_bayram_olsa.pdf","POP"],
["Haydar (Ben Melamet Hırkasını)","","","","Neyzen Tevfik","Nesimi","0:haydar_haydar.pdf","POP"],
["Haydi Abbas vakit tamam","","","","Fatih Kısaparmak","Cahit Sıtkı Tarancı","0:haydi-abbas-vakit-tamampdf1646997533.pdf","POP"],
["Haykıracak Nefesim Kalmasa Bile","","","","J.P. Lang / F. Bernhehim","Fikret Şeneş","0:haykiracak_nefessim_olmasa_bile.pdf","POP"],
["Her Yer Karanlık","","","","","","0:her_yer_karanlik.pdf","POP"],
["Her Yerde Kar Var","","","","","","0:her_yerde_kar_var.pdf","POP"],
["Her zaman bakarken mavi sulara","","","","Orhan Gencebay","Orhan Gencebay","0:her-zaman-bakarken-mavi-sularapdf1560194869.pdf","POP"],
["Hey Onbeşli","","","","","","0:hey_onbesli.pdf","POP"],
["Hislerime rüzgar eser","","","","Esin Engin","Halit Çelikoğlu","0:hislerimeruzgareserpdf1456690258.pdf","POP"],
["Hıstorıa De Un Amor","","","","","","0:historia_de_un_amor.pdf","POP"],
["Hor Görme Garibi","","","","Orhan Gencebay","Orhan Gencebay","0:hor_gorme_garibi.pdf","POP"],
["Hoş geldin (Piano için )","","","","","","0:hosgeldin-piano-turca-coverpdf1512480956.pdf","POP"],
["Hoş Gör Sen","","","","Enrico Mecias","Fikret Şeneş","0:hos_gor_sen.pdf","POP"],
["How Deep Is Your Love","","","","Bee Gees","","0:how_deep_is_your_love.pdf","POP"],
["If A Where Boy ( Beyonce )","","","","","","0:if_a_where_boy.pdf","POP"],
["Ihlamurlar Altında","","","","","","0:ihlamurlar_altinda.pdf","POP"],
["İki Yabancı","","","","","","0:iki_yabanci.pdf","POP"],
["İkimiz Bir Fidanın Güller Açan Dalıyız","","","","Hakkı Bulut","Hakkı Bulut","2:populer-muzik/228.html","POP"],
["İkimizin Yerine","","","","","","0:ikimizin_yerine.pdf","POP"],
["İllede Roman Olsun","","","","Naci Göçen","Naci Göçen","0:illede_roman_olsun.pdf","POP"],
["İmkansız Aşk","","","","","","0:imkansiz_ask.pdf","POP"],
["İnan Ki Ağlamadım ( Güz Gülleri )","","","","Selim Öztaş","Selim Öztaş","0:inan_ki_aglamadim.pdf","POP"],
["İncildim İncitildim Derinden","","","","D. Demirkan / S. Erener","S. Aksu / P.Barışta","0:incildim_incitildim_derinden.pdf","POP"],
["Isırgan Otu  2","","","","Ali Özütemiz","Ali Özütemiz","0:isirgan_otu.pdf","POP"],
["Işlak ışlak ( Piano için )","","","","Cem Karaca","","0:cem-karaca-islak-islak-piano-turca-cover-orjinalpdf1512480721.pdf","POP"],
["İstanbul Sokakları","","","","Selahattin Sarıkaya","Selahattin Sarıkaya","0:istanbul_sokaklari.pdf","POP"],
["İşte Bu Bizim Hikayemiz","","","","Coşkun Sabah","Ülkü Aker","0:iste_bu_bizim_hikayemiz.pdf","POP"],
["İsterdim Yanından Ayrılmayayım","","","","Murat Hacıfazlıoğlu","Murat Hacıfazlıoğlu","0:isterdimyanindanayrilmayayimpdf1556043014.pdf","POP"],
["İstiklal Marşı","","","","Zeki Üngör","Mehmet Akif Ersoy","0:istiklal_marsi_nota.pdf","POP"],
["İsyankâr","","","","Orhan Gencebay","Orhan Gencebay","0:isyankar.pdf","POP"],
["Johny Guıtar","","","","","","0:johny_guitar.pdf","POP"],
["Kader Böyle İmiş","","","","Coşkun Erdem","","0:kader_boyle_imis.pdf","POP"],
["Kader Diyemezsin Sen Kendin ettin","","","","","","0:kader_diyemezsin_sen_kendin_ettin.pdf","POP"],
["Kaderimin Oyunu","","","","Orhan Gencebay","Orhan Gencebay","0:ne-sevenim-var-ne-soranim-var-kaderimin-oyunupdf1560193113.pdf","POP"],
["Kaderimle Arkadaş Dost Olamadım","","","","Zafer Dilek","Ülkü Aker","0:kaderimle_arkadas_dost_olamadim.pdf","POP"],
["Kadın Bir Gül Aşk Bir Mevsim","","","","Teoman Alpay","Melih Özer","0:kadin_bir_gul.pdf","POP"],
["Kahverengi Gözlerin","","","","Selahattin Sarıkaya","Selahattin Sarıkaya","0:kahverengi_gozlerin.pdf","POP"],
["Kal Bu Gece","","","","","","0:kal_bu_gece.pdf","POP"],
["Kalb Kalbe Karşı","","","","","","0:kalp_kalbe_karsi.pdf","POP"],
["Kalbim Egede Kaldı","","","","Atilla Özdemiroğlu","S. Aksu-Şehrazat-S.Karataş","0:kalbimegedekaldipdf1556043154.pdf","POP"],
["Kalbimde Gizli Bir Sevgili Arar","","","","Suat Sayın","Suat Sayın","0:kalbimde_gizli_bir_sevgimi_arar.pdf","POP"],
["Kalbimi Kıra Kıra","","","","Teoman Alpay","","0:kalbimi_kira_kira.pdf","POP"],
["Kara Basma","","","","","","0:kara_basma.pdf","POP"],
["Kara sevda ( Dizi Müziği) (Piano İçin)","","","","","","0:kara-sevda-dizi-muzigi-anlatamam-piano-turca-coverpdf1517939296.pdf","POP"],
["Karadır Bu Bahtım Kara","","","","Neşet Ertaş","Neşet Ertaş","0:karadir_bu_bahtim_kara.pdf","POP"],
["Karakolda Ayna Var","","","","Zeki Duygulu","Zeki Duygulu","0:karakolda_ayna_var(1).pdf","POP"],
["Karlar Düşer","","","","","","0:karlar_duser.pdf","POP"],
["Kazaçok","","","","","","0:kazacok.pdf","POP"],
["Kederli Günlerimde Arkadaş Oldun","","","","Suat Sayın","Suat Sayın","0:kederli_gunlerimde_arkadas_oldun_bana.pdf","POP"],
["Kemancı","","","","Rıfat Şanlıel","Mehmet Yüzüak","0:kemanci.pdf","POP"],
["Kendine iyi bak (Piano İçin )","","","","Ahmet Kaya","Ali Çınar","0:ahmet-kaya-kendine-iyi-bakpdf1456684968.pdf","POP"],
["Kimi Dertden İçermiş","","","","Yusuf Nalkesen","Yusuf Nalkesen","0:kimi_dertten_icermis.pdf","POP"],
["Kimi gönülden sevdi kimi aldattı","","","","Esin Engin","İlkan San","0:kimigonuldensevdikimialdattipdf1456690296.pdf","POP"],
["Kır Gönlünün Zincirini","","","","Orhan Gencebay","Orhan Gencebay","0:kir_gonlunun_zincirini.pdf","POP"],
["Kiralık aşk- Dizi Müziği (Piano için )","","","","","","0:kiralik-ask-dizi-muzikleri-seni-seviyorum-by-piano-turcapdf1512481029.pdf","POP"],
["Kırılsın Ellerim Ne Ye Yarıyor","","","","Gülden Karaböcek","","0:kirilsin_ellerim.pdf","POP"],
["Kış Masalı (Göz Yaşım Kederden Miydi..)","","","","Âdem Gümüşkaya","Âdem Gümüşkaya","0:kis_masali__(gozyasim_kederden_miydi_yarim).pdf","POP"],
["Kıskanırım Seni Ben","","","","Teoman Alpay","H. Münir Ebcioğlu","0:kiskanirimsenibenpdf1509747781.pdf","POP"],
["Kıskanmakta Haksızmıyım Gülizar","","","","Hulki Saner","","0:kiskanmakta_haksizmiyim_gulizar.pdf","POP"],
["Kol Düğmeleri","","","","Barış Manço","","0:kol_dugmeleri.pdf","POP"],
["Konyalı","","","","","","0:konyali.pdf","POP"],
["Kum Gibi","","","","Ahmet Kaya","Ahmet Kaya","0:kum_gibi.pdf","POP"],
["Kumruları Dinledim Susuverdiler","","","","Selahattin Altınbaş","Özdemir Kiper","2:populer-muzik/272.html","POP"],
["Kumsal","","","","Selami Şahin","Taner Şener","0:kumsal.pdf","POP"],
["Kutupta Yaz Gibi","","","","Halil Karaduman","Aşkın Tuna","0:kutupta_yaz_gibi.pdf","POP"],
["La Cumparsıta","","","","","","0:la_cumparsita.pdf","POP"],
["La Vie En Rose","","","","","","0:la_vie_en_rose.pdf","POP"],
["Lambada","","","","","","0:lambada.pdf","POP"],
["Leylâ İle Mecnun","","","","Orhan Gencebay","Orhan Gencebay","0:leyla_ile_mecnun.pdf","POP"],
["Leylim Ley","","","","Zülfü Livaneli","Sebahattin Ali","0:leylim_ley.pdf","POP"],
["Love Story","","","","","","0:love_story.pdf","POP"],
["Maazallah","","","","","Şehrazat","0:maazallah.pdf","POP"],
["Mahkemeye Versem Seni Asarlar","","","","Selahattin Sarıkaya","Selahattin Sarıkaya","0:mahkemeye_versem_seni_asarlar.pdf","POP"],
["Malaguena","","","","","","0:malaguena.pdf","POP"],
["Mavi Boncuk","","","","Hulki Saner","Hulki Saner","0:mavi_boncuk.pdf","POP"],
["Med Cezir","","","","Levend Yüksel","","0:med_cezir.pdf","POP"],
["Mehtaplı Gecelerde","","","","Sevim Şengül","","0:mehtapli_gecelerde.pdf","POP"],
["Memleketim","","","","","","0:memleketim.pdf","POP"],
["Mevlam Bir Çok Dert Vermiş","","","","","","0:mevlam_bir_cok_dert_vermis.pdf","POP"],
["Meydan mı verirdim bu ayrılığa","","","","Orhan Gencebay","Cemal Safi","0:meydan-mi-verirdim-bu-ayriligapdf1560194908.pdf","POP"],
["Mıdnıght Blue","","","","","","0:midnight_blue.pdf","POP"],
["Mihriban","","","","Musa Eroğlu","Abdurrahim Karakoç","0:mihriban.pdf","POP"],
["Mihriban (Piano için)","","","","Musa Eroğlu","Abdurrahim Karakoç","0:musa-eroglu-mihriban-pianopdf1456687093.pdf","POP"],
["Mor Akşamlar","","","","Şehrazat","Şehrazat","0:mor_aksamlar.pdf","POP"],
["Mor Menekşe","","","","Kayahan Acar","Kayahan Acar","0:mor_menekse.pdf","POP"],
["Namusumsun","","","","","","0:namusumsun.pdf","POP"],
["Nar Danesi","","","","","","0:nar_danesi.pdf","POP"],
["Ne Olursun Güzelim","","","","Rüştü Demirci","Rüştü Demirci","0:ne_olursun_guzelim.pdf","POP"],
["Neden Kaçtın Uzaklara","","","","Yusuf Nalkesen","Yusuf Nalkesen","0:neden_kactin_uzaklara.pdf","POP"],
["Nemrud\u0027un Kızı","","","","Kazancı Bedih","Kazancı Bedih","0:nemrudun_kizi.pdf","POP"],
["Nerden Bileceksin","","","","Orhan Gencebay","Vural Şahin","0:nerden_bileceksin.pdf","POP"],
["Neşeli Günler","","","","","","0:neseli_gunler.pdf","POP"],
["Neşeli Ol Ki Genç Kalasın","","","","","","0:neseli_ol_ki.pdf","POP"],
["Nev-Eser Saz Eseri","","","","Orhan Gencebay","Orhan Gencebay","0:neveser_saz_eseri_orhan_gencebay.pdf","POP"],
["Neyleyim Neyleyim Ben Böyle Yâri","","","","Ahmet Gazi Ayhan","Ahmet Gazi Ayhan","0:neyleyim_neyleyim.pdf","POP"],
["Nihavend Longa","","","","Doğan Canku","","0:nihavent_longa.pdf","POP"],
["Nihavend Uvertür","","","","Orhan Gencebay","","0:nihavend-uvertur-1pdf1557176453.pdf","POP"],
["Nisan Yağmuru","","","","Rıza Ateş","Rafet Başaran","0:nisan_yagmuru.pdf","POP"],
["O Simsiyah Gözlerin","","","","","","0:o_simsiyah_gozlerin.pdf","POP"],
["O Yaz","","","","Bora Ayanoğlu","Bora Ayanoğlu","0:o_yaz.pdf","POP"],
["Okyanus","","","","Talat Er","Nadide Gülpınar","0:okyanus.pdf","POP"],
["Ölesiye Sevmiştim Seni","","","","Suat Sayın","","0:olesiye_sevmistim_seni.pdf","POP"],
["Olmasa Mektubum","","","","","","0:olmasa_mektubum.pdf","POP"],
["Olmuyor Sensiz Olmuyor","","","","Selami Şahin","Selami Şahin","0:olmuyor_sensiz_olmuyor.pdf","POP"],
["Ölüyorum Kederimden","","","","Mustafa Sayan","","0:oluyorum_kederimden.pdf","POP"],
["Ona eyvallah buna eyvallah","","","","Orhan Gencebay","Orhan Gencebay","0:ona-eyvallah-buna-eyvallah-eyvallah-pdf1572122336.pdf","POP"],
["Önce Tuttun Elimden","","","","Suat Sayın","","0:oncetuttunelimdenpdf1506343139.pdf","POP"],
["Öptüm Yanaklarından","","","","Turhan Taşan","Aşkın Tuna","0:optum.pdf","POP"],
["Öyle bir aşk isterim ki","","","","Orhan Gencebay","Orhan Gencebay","0:oyle-bir-ask-isterim-kipdf1560253906.pdf","POP"],
["Öyle dudak büküp hor gözle bakma (Piano için)","","","","Avni Anıl","Şâhin Çandır","0:ah-bu-sarkilarin-gozu-kor-olsun-pianopdf1456684116.pdf","POP"],
["Öyle Sarhoş Olsam Ki","","","","Bülent Şençalar","Güzin Gürman","0:oyle_sarhos_olsamki.pdf","POP"],
["Oyun Bitti","","","","İsmet Nedim Saatçi","Bülent Pozan","0:oyun_bitti.pdf","POP"],
["Özledim teninin kokusunu özledim","","","","Selami Şahin","Selami Şahin","0:ozledim_teninin_kokusunu_ozledim.pdf","POP"],
["Pala Remzi","","","","","","0:pala_remzi.pdf","POP"],
["Pamuk","","","","Kenan Doğulu","Kenan Doğulu","0:pamuk.pdf","POP"],
["Papatya Gibisin","","","","","","0:papatya_gibisin.pdf","POP"],
["Paramparça","","","","Teoman","Teoman","0:paramparca.pdf","POP"],
["Pervane","","","","Özdemir Erdoğan","","0:pervane.pdf","POP"],
["Pervane - Bana Ellerini ver ( Piano için )","","","","Zuhal Olcay","","0:zuhal-olcay-pervane-bana-ellerini-ver-piano-turca-piyano-yorumu-kolaypdf1512481258.pdf","POP"],
["Pişman Olacaksın Günün Birinde","","","","Selâhattin Cesur","A. Selçuk İlkan","0:gunun_birinde(1).pdf","POP"],
["Rakkas","","","","Atilla Özdemiroğlu","S. Aksu - Y. Karataş","0:rakkas.pdf","POP"],
["Rüyalar Gerçek Olsa","","","","Hulki Saner","Hulki Saner","0:ruyalar_gercek_olsa.pdf","POP"],
["Rüyalarda Buluşuruz","","","","Halil Karaduman","A. Aşkın Tuna","0:ruyalarda_bulusuruz.pdf","POP"],
["Sabır Taşı","","","","Orhan Gencebay","Orhan Gencebay","0:sabir_tasi.pdf","POP"],
["Şakayık","","","","Erdoğan Berker","Ayten Baykal","0:sakayik.pdf","POP"],
["Sakın Bir Söz Söyleme (İntizar)","","","","Suat Sayın","F. Nâfiz Çamlıbel","0:sakin_bir_soz_soyleme.pdf","POP"],
["Sana Neler Edeceğim","","","","Elias Rahbani","Fikret Şeneş","0:sana_neler_edecegim.pdf","POP"],
["Sana Nerden Gönül Verdim","","","","Fehmi Ege","","0:sana_nerden_gonul_verdim.pdf","POP"],
["Sana Öyle Hasretim Ki","","","","Erdoğan Berker","Ayten Baykal","0:sana_oyle_hasretim_ki.pdf","POP"],
["Sanırdım gündüzdü onlarla gecem (Dost bildiklerim)","","","","Muzaffer Özpınar","Ümit Yaşar Oğuzcan","0:dost-bildiklerimpdf1646746707.pdf","POP"],
["Santa Lucıa","","","","","","0:santa_lucia.pdf","POP"],
["Şarap Koy Kadehime Kan Doldurma","","","","Ergin Kızılay","Hikmet Aran","0:sarap_koy_kadehime.pdf","POP"],
["Sarı Gelin","","","","","","0:sari_gelin.pdf","POP"],
["Sarı gelin (Piano için)","","","","","","0:sari-gelin-piano-turca-piyano-yorumu-kolaypdf1517939398.pdf","POP"],
["Şarkılardan Fal Tuttum","","","","Erdoğan Berker","Mehmet Erbulan","2:populer-muzik/377.html","POP"],
["Saygı Marşı","","","","","","0:saygi_marsi.pdf","POP"],
["Sefam Olsun Oh Oh","","","","Selami Şahin","Selami Şahin","0:sefam_olsun_oh_oh.pdf","POP"],
["Selamı Sabahı Kesiver Gitsin","","","","Zeynettin Maraş","İlkan San","0:selami_sabahi_kesiver_gitsin.pdf","POP"],
["Selvi boylum al yazmalım (Piano için)","","","","Cahit Berkay","Cahit Berkay","0:cahit-berkay-alyazmalim-pianopdf1456685436.pdf","POP"],
["Sen Benden Gittin Gideli","","","","Edip Akbayram","","0:sen_benden_gittin_gideli.pdf","POP"],
["Sen De Git","","","","Rıfat Şanlıel","İlkan San","0:sen_de_git.pdf","POP"],
["Sen derdim de neş\u0027em de sen","","","","Orhan Gencebay","Orhan Gencebay","0:sen-derdim-de-nes-em-de-senpdf1572122415.pdf","POP"],
["Sen Gelmez Oldun","","","","Ali Ekber Tapiyev","Ali Ekber Tapiyev","0:sen_gelmez_oldun.pdf","POP"],
["Sen Mevsimler Gibisin","","","","Selami Şahin","Selami Şahin","0:sen_mevsimler_gibisin.pdf","POP"],
["Sen ne dersen de (Dünya dönüyor)","","","","Orhan Gencebay","Orhan Gencebay","0:sen-ne-dersen-de-dunya-donuyor-donecek-2pdf1557439623.pdf","POP"],
["Sen Uzaklarda Değil Damarımda Kanımsın","","","","Sinan Subaşı","Sinan Subaşı","0:sen_uzaklarda_degil_damarimda_kaninsin.pdf","POP"],
["Senden Başka","","","","Manolos Hadjdakis","Tuğrul Dağcı","0:senden_baska.pdf","POP"],
["Seni Andım Bu Gece","","","","Şekip Ayhan Özışık","Ülkü Aker","0:seni_andim_bu_gece_kulaklarin_cinlasin(1).pdf","POP"],
["Seni Sordum Yıldızlara","","","","Mehmet Bitmez","Mustafa Güler","0:seni_sordum_yildizlara.pdf","POP"],
["Senin Aşkına Hiç Doyum Olmaz","","","","","","0:senin_askina_hic_doyum_olmaz.pdf","POP"],
["Seninle Bir Dakika","","","","Kemal Ebcioğlu","","0:seninle_bir_dakika.pdf","POP"],
["Seninle Tattım Ben Her Mutluluğu","","","","Zekai Tunca","Aşkın Tuna","0:seninle_tattim_ben_her_mutlulugu(2).pdf","POP"],
["Sensiz geçen gecelerde","","","","Esin Engin","Gönül Şen","0:sensizgecengecelerdepdf1456690330.pdf","POP"],
["Sensiz Olmadı","","","","Selçuk Tekay","Cemal Safi","0:sensiz_olmadi.pdf","POP"],
["Sensiz Olmuyor","","","","Selami Şahin","Selami Şahin","0:sensiz_olmuyor.pdf","POP"],
["Sensiz Saadet Neymiş Tatmadım Bilemem ki","","","","Yaşar Güvenir","Yaşar Güvenir","0:sensiz_saadet_neymis__asklarin_en_guzeli_(1).pdf","POP"],
["Sev Dedi Gözlerim","","","","Orhan Gencebay","Orhan Gencebay","0:sev_dedi_gozlerim.pdf","POP"],
["Sevda Yüklü Kervanlar","","","","Halit Araboğlu","Halit Araboğlu","0:sevda_yuklu_kervanlar.pdf","POP"],
["Sevdan İle Düştüm","","","","Özer Şenay","","0:sevdan_ile_dustum.pdf","POP"],
["Sevdi Gönlüm","","","","Erhan Parlat","Erhan Parlat","0:sevdi_gonlum.pdf","POP"],
["Sevdiğim ellerde nazın çekilmez","","","","Orhan Gencebay","Cemal Safi","0:sevdigim-ellerde-nazin-cekilmezpdf1560194992.pdf","POP"],
["Sevdim Bir Genc Kadını","","","","Necip Celâl Andel","Bedri Noyan","0:sevdim_bir_genc_kadini.pdf","POP"],
["Sevdim seni bir kere (Piano için)","","","","Özdemir Erdoğan","Özdemir Erdoğan","0:teoman-sevdim-seni-bir-kerepdf1487186699.pdf","POP"],
["Sevemedim Kara Gözlüm","","","","Orhan Gencebay","A. Nail Bayşu","0:sevemedim_kara_gozlum.pdf","POP"],
["Sevemez Kimse Seni","","","","Suat Sayın","","0:sevemez_kimse_seni.pdf","POP"],
["Seven Ne Yapmaz","","","","Teoman Alpay","Sadık Şendil","0:seven_ne_yapmaz.pdf","POP"],
["Sevenler Mesut Olmaz","","","","Orhan Gencebay","Orhan Gencebay","0:sevenler_mesud_olmaz.pdf","POP"],
["Sevenlerin sağı solu belli olmaz (Sarhoşun biriyim)","","","","Orhan Gencebay","Orhan Gencebay","0:sevenlerin-sagi-solu-belli-olmaz-belli-olmazpdf1560195036.pdf","POP"],
["Severek Ayrılalım","","","","Orhan Gencebay","Orhan Gencebay","0:severek_ayrilalim.pdf","POP"],
["Sevme gönlüm  sevme yanarsın","","","","Orhan Gencebay","Orhan Gencebay","0:sevme-gonlum-sevme-sevme-yanarsinpdf1560195085.pdf","POP"],
["Sevmek çok zormuş sevmemek çok zor (Dilenci)","","","","Orhan Gencebay","Orhan Gencebay","0:sevmek-cok-zormus-sevmemek-cok-zorpdf1560195137.pdf","POP"],
["Sigaramda Duman Duman","","","","Polat Tezel","Polat Tezel","0:sigaramda_duman_duman.pdf","POP"],
["Sigaramın Dumanına Sarsam","","","","","","0:sigaramin_dumanina_sarsam.pdf","POP"],
["Şikayetim Var Kaderden Yana","","","","Selami Şahin","Ülkü Aker","0:sikayetim_var_kaderden_yana.pdf","POP"],
["Sitem","","","","Onno Tunç","Aysel Gürel","0:sitem.pdf","POP"],
["Siyah saçlarında hatem yüzleri ( Hudey )","","","","","","0:hudeypdf1512505159.pdf","POP"],
["Sokağın Ardındayım","","","","Suat Sayın","Suat Sayın","0:sokagin_ardindayim.pdf","POP"],
["Sonbahar Rüzgârları","","","","Yıldırım Gürses","Erkan Yurdaer","0:sonbahar_ruzgarlari.pdf","POP"],
["Sonsuza Dek","","","","Doğan Canku","Ayşegül Canku","0:sonsuza_dek.pdf","POP"],
["Söyle nasıl yaşarım","","","","Esin Engin","Şadi Kurtuluş","0:soylenasilyasarimpdf1456690374.pdf","POP"],
["Söyleyin Yıldızlar Sevgilim Nerde","","","","Suat Sayın","Suat Sayın","0:soyleyin_yildizlar_sevgilim_nerde.pdf","POP"],
["Su Sızıyor Sızıyor","","","","","","0:su_siziyor.pdf","POP"],
["Sultan Süleyman (Piano için)","","","","Onno Tunç","Aysel Gürel","0:sultan-suleyman-pianopdf1456687722.pdf","POP"],
["Sultanım (Piano için )","","","","Mustafa Ceceli","","0:mustafa-ceceli-sultanim-piano-turca-coverpdf1512481091.pdf","POP"],
["Sus Sus Sus Kimseler Duymasın","","","","Suat Sayın","Suat Sayın","0:sus_sus_sus_kimseler_duymasin.pdf","POP"],
["Susadım Çeşmeye Gelmez Olaydım","","","","Ferdi Tayfur","Ferdi Tayfur","0:susadim_cesmeye_gelmez_olaydim.pdf","POP"],
["Tac Olsan Başıma Takmayacağım","","","","Sadettin Öktenay","","0:tac_olsan_basima_takmayacagim.pdf","POP"],
["Taht Kurmuşsun Kalbime","","","","Orhan Akdeniz","Şemsettin Polat","0:taht_kurmussun_kalbime.pdf","POP"],
["Takalar Geçiyor","","","","Doğan Canku","Bülent Ecevit","0:takalar_geciyor_alli_yesilli.pdf","POP"],
["Takvimlerden Haberin Yok Mu","","","","Adnan Ergil","Adnan Ergil","0:takvimlerden_haberin_yok_mu.pdf","POP"],
["Tanrı İstemezse","","","","Mustafa Sayan","Ali Avaz","0:tanri_istemezse.pdf","POP"],
["Tanrım Beni Baştan Yarat","","","","Muzaffer Özpınar","Ali Tekintüre","0:tanrimbenibastanyaratpdf1645476517.pdf","POP"],
["Tek Başına","","","","Luigi Albertelli","Ülkü Aker","0:tek_basina_ayten_alpman.pdf","POP"],
["Tek Kurşunla Bir Bedende Vuruldum","","","","Bilge Özgen","Yalçın Benlican","0:tek_kursunla_bir_bedende_vurulduk.pdf","POP"],
["Telli Telli","","","","","","0:telli_telli.pdf","POP"],
["The Shadow Of Your Smile","","","","","","0:the_shadow_of_your_smile.pdf","POP"],
["Tıtanıc","","","","","","0:titanic.pdf","POP"],
["Tuna Dalgaları Valsi","","","","","","0:tuna_dalgalari.pdf","POP"],
["Türk Kahvesi","","","","Halil Karaduman","Attila Şanbay","0:turk_kahvesi.pdf","POP"],
["Türk Marşı","","","","W. A. Mozart","","0:turk_marsi.pdf","POP"],
["Türkiyem Türkiyem Cennetim","","","","Müşerref Akay","Mahmut Tezcan","0:turkiyem.pdf","POP"],
["Ufka uzanan yol sana gelen yol sanıp","","","","Orhan Gencebay","Vural Şahin","0:ufka-uzanan-yolu-sana-gelen-yol-sanippdf1572122658.pdf","POP"],
["Un Break My Heart","","","","","","0:un_break_my_heart.pdf","POP"],
["Unut Beni","","","","","","0:unut_beni.pdf","POP"],
["Unutamazsın","","","","Yavuz Taner","Ali Tekintüre","0:unutamazsin.pdf","POP"],
["Unutma Beni Unutama Beni","","","","Şem\u0027i Diriker","Şem\u0027i Diriker","0:unutma_beni_unutama_beni.pdf","POP"],
["Unutmaya yemin ettim","","","","Esin Engin","Aşkın Tuna","0:unutmayayeminettimpdf1456690407.pdf","POP"],
["Unutursun Diye Çok Korkmuyorum","","","","Halil Yılmaz ( Aşık Salihi )","Halil Yılmaz ( Aşık Salihi )","0:unutursundiyecokkorkuyorumpdf1512508368.pdf","POP"],
["Unuturum Diye Yorma Kendini","","","","Selçuk Tekay","Ünal Narçın","0:unuturum_diye_yorma_kendini.pdf","POP"],
["Uykudamısın Sevgili Yârim","","","","Kâzım Sanrı","Kâzım Sanrı","0:uykudamisin_sevgili_yarim.pdf","POP"],
["Üzülme","","","","F. Anıl Yarkın","A.Tuna / F.A.Yarkın","0:uzulme.pdf","POP"],
["Vakit Yok Gemi Kalkıyor","","","","","","0:vakit_yok_gemi_kalkiyor.pdf","POP"],
["Vaktinde Gel Sevgilim","","","","Orhan Gencebay","Mehmet Erbulan","0:vaktinde_gel_sevgilim.pdf","POP"],
["Vazgeç Gönlüm Sen Bu Aşktan","","","","Orhan Gencebay","Orhan Gencebay","0:vazgec-gonlum-sen-bu-asktanpdf1572122712.pdf","POP"],
["Vicdan Azâbı","","","","Orhan Gencebay","Orhan Gencebay","0:vicdan_azabi.pdf","POP"],
["Vurgun Yemiş Gibiyim","","","","Selami Şahin","Selami Şahin","0:vurgun_yemis_gibiyim.pdf","POP"],
["What Now My Love","","","","","","0:what_now_my_love.pdf","POP"],
["Ya Evde Yoksan","","","","Orhan Gencebay","Orhan Gencebay","0:ya_evde_yoksan.pdf","POP"],
["Ya Habibi","","","","Selami Şahin","","0:ya_habibi.pdf","POP"],
["Yâ Rabbim","","","","Orhan Gencebay","Orhan Gencebay","0:yarabbim-sen-buyuksunpdf1560193044.pdf","POP"],
["Yağmur olsan toprağınım","","","","Metin Alkanlı","Metin Alkanlı","0:yagmurolsantopraginimpdf1487529531.pdf","POP"],
["Yağmurun Sesine Bak","","","","Vedat Yıldırımbora","Vedat Yıldırımbora","0:yagmurun_sesine_bak_aska_davet_ediyor.pdf","POP"],
["Yakanlar Yakmış","","","","Yusuf Nalkesen","Yusuf Nalkesen","0:yakanlar_yakmis.pdf","POP"],
["Yalancı Bahar","","","","Serkan","Ertuğ Ergün","0:yalanci_bahar.pdf","POP"],
["Yalancı Yârim","","","","Hikmet Kutlu","Hikmet Kutlu","0:yalanci_yarim.pdf","POP"],
["Yallah","","","","Selami Şahin","","0:yallah.pdf","POP"],
["Yalnızım Dostlarım","","","","","","0:yalnizim_dostlarim.pdf","POP"],
["Yalnızlık Ömür Boyu","","","","M.F.Ö.","M.F.Ö.","0:yalnizlik_omur_boyu.pdf","POP"],
["Yalnızlık","","","","Selami Şahin","A. Selçuk İlkan","0:yalnizlik.pdf","POP"],
["Yaşadığım sanki masal","","","","Esin Engin","Gülden Yıldız Çeliker","0:yasadigimsankimasalpdf1456690452.pdf","POP"],
["Yaşadım Mı Öldüm Mü","","","","Zafer Dilek","Ülkü Aker","0:yasadim_mi_oldum_mu.pdf","POP"],
["Yaşamak istiyorsan feleğe küsme","","","","Orhan Gencebay","Orhan Gencebay","0:yasamak-istiyorsan-felege-kusme-uc-gunluk-dunya-pdf1572122794.pdf","POP"],
["Yaşamaktan Korkuyorum","","","","Rıfat Şanlıel","","0:yasamaktan_korkmuyorum.pdf","POP"],
["Yaşlı Gözlerinde Hep","","","","Ali Erköse","Kemal Şenay","0:yasli_gozlerimde_hep_yasiyor_hatiralar.pdf","POP"],
["Yatağıma Gel","","","","Paco De Lucıa","","0:yatagima_gel.pdf","POP"],
["Yaz Yaz Yaz","","","","Şehrazat","Şehrazat","0:yaz_yaz_yaz.pdf","POP"],
["Yazıl Bana","","","","Kemal Taşçeşme","","0:yazil_bana.pdf","POP"],
["Yedi Kocalı Hürmüz","","","","Sadık Şendil","Sadık Şendil","0:yedi_kocali_hurmuz.pdf","POP"],
["Yedikule","","","","Vangalis Papazoğlu","Cengiz Onursal","0:yedikule.pdf","POP"],
["Yedin Beni","","","","Oktay","Oktay","0:yedin_beni.pdf","POP"],
["Yeşil Başlı Gövel Ördek","","","","","","0:yesil_basli_govel_ordek.pdf","POP"],
["Yeter artık","","","","Esin Engin","Gönül Şen","0:yeterartikpdf1456690521.pdf","POP"],
["Yıllarca böyle bir aşkı bekledik","","","","Esin Engin","Aşkın Tuna","0:yillarcaboylebiraskibekledikpdf1456690562.pdf","POP"],
["Yıllardır yüzünü görmesem bile","","","","Esin Engin","Aşkın Tuna","0:yillardiryuzunugormesembilepdf1456690612.pdf","POP"],
["Yılların özlemi senle son buldu","","","","Esin Engin","Aşkın Tuna","0:yillarinozlemisenlesonbuldupdf1456690649.pdf","POP"],
["Yollar Uzak Gelemedim","","","","Suat Sayın","Suat Sayın","0:yollar_uzak_gelemedim.pdf","POP"],
["Yollarda Bulurum Seni","","","","Haluk Levent","","0:yollarda_bulurum_seni.pdf","POP"],
["Yolların en sonunda seni aradım yoksun","","","","Muzaffer Özpınar","Nurettin Baykal","0:senyoksunpdf1512505324.pdf","POP"],
["Yolun Sonu Görünüyor","","","","Selahattin Aygün","Dursunali Akınet","0:yolun_sonu_gorunuyor.pdf","POP"],
["Yoruldum","","","","Halil Karaduman","Yalçın Benlican","0:yoruldum.pdf","POP"],
["Yüce dağdan esen yelden (Sarsam seni )","","","","Yıldırım Gürses","Mustafa Sevilen","0:yucedagdanesenyeldenpdf1514412363.pdf","POP"],
["Zakkum (Gökyüzünde)  (Piano için)","","","","","","0:zakkum-gokyuzundepdf1517941258.pdf","POP"],
["Zakkum - Gökyüzünde (Piano için )","","","","","","0:zakkum-gokyuzunde-piano-turca-piyano-yorumupdf1512481173.pdf","POP"],
["Zalimin Zulmü Varsa","","","","Suat Sayın","Suat Sayın","0:zalimin_zulmu_varsa.pdf","POP"],
["Zaman Akıp Gider Durulmadan","","","","Orhan Gencebay","Orhan Gencebay","0:zaman-akip-gider-durulmadanpdf1560193008.pdf","POP"],
["Zikr","","","","A. R. Rahman - Ethan Sperry","A. R. Rahman","0:zikraarahmanethansperrypdf1514580118.pdf","POP"]
    ]
  });
  if (window.CatalogManager && window.CatalogManager.onChunkLoaded) {
    window.CatalogManager.onChunkLoaded();
  }
})();